# Конфигурация ядра приложения
SECRET_KEY: 4r5345kjnvefkmg49bsfdbmlekdfn2
DEBUG: False
HOST: 0.0.0.0
PORT: 5065
SSL: adhoc

API_KEY: 15c6941847849f1e498c69e42ad4a78f
weather_url: https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API_key}
geo_url: http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=1&appid={API_key}
scheduler_interval: 1  # В минутах

# Конфигурация БД
# db:
#   engine: postgresql
#   host: dev.dib.local
#   port: 5432
#   name: TESTS
#   user: admin
#   pass: admin

